### PR TITLE
Email templates done

### LINKED ISSUE #93: Create HTML email format for welcome email
## Context
When users sign up they receive a welcome email with a verification token

## Problem

Currently, the welcome email is just plain text

## Solution 

- [x] Create HTML for email verification link as button
- [ ] Integrate html in email verification function

### LINKED ISSUE #94: Create HTML email format for reset password
## Context
When users reset their password they receive an email with a verification token

## Problem

Currently, the  email is just plain text

## Solution 

- [ ] Create HTML for reset password verification link as button
- [ ] Integrate html in reset password verification function

### PR DESCRIPTION
**Pull request by jyaneshseeam**
## Source 
Closes #94 and #93

## Description 

Templates for email verification and reset password

### Summary of PR 

New templates were created for sending emails and resetting the password

### Purpose 

A more professional looking message in HTML to be sent via email 
### Review and Testing Steps

- [ ] Pull this branch
- [ ] Run  ``` cd app\server ```
- [ ] create a .env file and get the values from the shared doc
- [ ]  run ``` npm install```
- [ ] run ``` docker build -t server . ```
- [ ] run ``` docker run -dp 8080:8080 server ```
- [ ] All post and get requests must be with port 8080 instead of 3000
- [ ] Then try to register with new user details + a real email ( you can use temporary emails online website) I used https://temp-mail.org/
- [ ] Then you should be getting  a welcome email
- [ ] Then try to use the forgot password API ( paste the username or email there)
- [ ]  Then you should be getting  a reset password email

### Additional Information (If applicable)
Let me know what do you think of the templates or if any changes needs to be done, (could be changed later too)

### Notes

Templates now integrated with emailing function

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@jyaneshseeam why are not using docker for testing and developing?

**Comment by jyaneshseeam** [comment]
> @jyaneshseeam why are not using docker for testing and developing?

@sontushkpaul just updated review steps with docker

**Review by sontushkpaul — APPROVED** [review]
Tested and approved

**Comment by DemiAdisa** [comment]
I get a "socket hang up" error when I try to send the requests using the running server on docker

**Comment by jyaneshseeam** [comment]
@DemiAdisa check port, it should be localhost 8080

**Comment by DemiAdisa** [comment]
image

Yes I did take note of that, plus when I check the image on the docker app, it says listening on port 3000 so not really sure what's going on

**Comment by sontushkpaul** [comment]
> image
> 
> Yes I did take note of that, plus when I check the image on the docker app, it says listening on port 3000 so not really sure what's going on

Did you change your env from Google docs ? If not please change it

**Comment by DemiAdisa** [comment]
> > image
> > Yes I did take note of that, plus when I check the image on the docker app, it says listening on port 3000 so not really sure what's going on
> 
> Did you change your env from Google docs ? If not please change it

I do have the updated values for .env
Still no luck

**Comment by jyaneshseeam** [comment]
> > > image
> > > Yes I did take note of that, plus when I check the image on the docker app, it says listening on port 3000 so not really sure what's going on
> > 
> > 
> > Did you change your env from Google docs ? If not please change it
> 
> I do have the updated values for .env Still no luck

Run the docker image in the docker desktop app then try again ?

**Comment by sontushkpaul** [comment]
@DemiAdisa are you still facing same problem?

**Comment by DemiAdisa** [comment]
> @DemiAdisa are you still facing same problem?

Yes I am, sorry for the late responses guys, I have some tests and I am multi tasking a lot now 😂. My apologies

**Comment by sontushkpaul** [comment]
> > @DemiAdisa are you still facing same problem?
> 
> Yes I am, sorry for the late responses guys, I have some tests and I am multi tasking a lot now 😂. My apologies

@DemiAdisa  Show us the problem in the today's meeting

**Comment by DemiAdisa** [comment]
> > > @DemiAdisa are you still facing same problem?
> 
> > 
> 
> > Yes I am, sorry for the late responses guys, I have some tests and I am multi tasking a lot now 😂. My apologies
> 
> 
> 
> @DemiAdisa  Show us the problem in the today's meeting

Definitely

**Review by ja-chisholm — APPROVED** [review]

**Pull request merged**
