### PR TITLE
Dev card component

### LINKED ISSUE #133: Emergency support List Card component
## Context 
We need support list 

## Problem 
We need reusable card component for the list. Each card will contain each support.

## Solution

- [x] Research about card component
- [x] Divide the card in two section : Title and description 
- [x]   add a button "Learn More" for more details

### PR DESCRIPTION
**Pull request by ja-chisholm**
## Source 
Closes #133 

## Description 
Adds a Standard Card component to be used in the emergency support screen

### Summary of PR 
Adds code and documentation for StdCard

### Purpose 
Serve information and allow navigation to "learn more" page

### Review and Testing Steps

- [ ] Pull branch
- [ ] Read StdCard.md and look for errors or typos
- [ ] Follow examples in StdCard.md

### Additional Information (If applicable)
N/A

### Notes
N/A

### Resources 
[More about React Native Paper's Card component](https://callstack.github.io/react-native-paper/card.html)

### CODE REVIEW

**Comment by sontushkpaul** [comment]
This is how it react when the description is big. 
image

For button "Learn More" we can use a forward arrow "->" in the bottom right corner 
image
some thing like that 
image

# Note
and keep only the "title" required because we will have the scenario when we will not use "subtitle" and buttonPress for the card. and card should be resizable or auto expend when there is big description

**Comment by ja-chisholm** [comment]
@sontushkpaul just made some updates as per your review - is there anything else that needs to be updated?

**Review by jyaneshseeam — APPROVED** [review]
Card looks good, arrow button is good too

**Comment by DemiAdisa** [comment]
image

Is the white background supposed to be toggled on or something cause this is what happens on my ends

**Comment by ja-chisholm** [comment]
@DemiAdisa I'm not sure what's causing that, do you mind sending me a pic of how you call the card component? I'll look into it

**Comment by sontushkpaul** [comment]
@ja-chisholm The height should actual height not minimum height of the card. It is causing wired problem please look into that.
image

**Comment by ja-chisholm** [comment]
@sontushkpaul height and width configuration has been updated

**Comment by ja-chisholm** [comment]
@sontushkpaul do you mind taking a look at the new changes? The issue where the card would have no background or button is no longer occurring for me

**Comment by DemiAdisa** [comment]
> @sontushkpaul do you mind taking a look at the new changes? The issue where the card would have no background or button is no longer occurring for me

I will try it out now

**Comment by DemiAdisa** [comment]
> @sontushkpaul do you mind taking a look at the new changes? The issue where the card would have no background or button is no longer occurring for me

image
Not sure why but the card is not stretching properly

**Comment by ja-chisholm** [comment]
@DemiAdisa the height and width props have been updated so that it won't stretch beyond them. What height/width did you supply when making it?

**Comment by DemiAdisa** [comment]
> @DemiAdisa the height and width props have been updated so that it won't stretch beyond them. What height/width did you supply when making it?

I did not supply any and left it at default, I thought it would auto stretch to fit

**Comment by DemiAdisa** [comment]
> > @DemiAdisa the height and width props have been updated so that it won't stretch beyond them. What height/width did you supply when making it?
> 
> I did not supply any and left it at default, I thought it would auto stretch to fit

But since it's the way it was updated, it should be good then

**Comment by DemiAdisa** [comment]
Since the cards don't auto stretch, are we all comfortable with different sized cards?

**Comment by DemiAdisa** [comment]
Not sure why but the width of the card does not change even after applying the width props to it

**Comment by ja-chisholm** [comment]
> Not sure why but the width of the card does not change even after applying the width props to it

Just updated, give it a try now

**Comment by DemiAdisa** [comment]
> > Not sure why but the width of the card does not change even after applying the width props to it
> 
> Just updated, give it a try now

Same situation unfortunately, no luck on this end

**Comment by ja-chisholm** [comment]
> Same situation unfortunately, no luck on this end

Just updated again, it works on my end but if you're still having issues let me know

**Comment by DemiAdisa** [comment]
> > Same situation unfortunately, no luck on this end
> 
> Just updated again, it works on my end but if you're still having issues let me know

Works great now but you might have to pull the dev branch so your CI/CD tests can pass

**Comment by ja-chisholm** [comment]
> Works great now but you might have to pull the dev branch so your CI/CD tests can pass

My bad, didn't notice that. It should be good now

**Review by DemiAdisa — APPROVED** [review]
Works as expected

**Pull request merged**
