### PR TITLE
Set up jest and React Native Testing Library(RNTL). 

### PR DESCRIPTION
**Pull request by sontushkpaul**
## Source 

If this PR comes froma an issue, another PR, or any GitHub Object link them in the section.

### Summary of PR 
To test the React Native app we need Testing Libraries. 

### Purpose 

The PR includes the Jest and RNTL testing libraries to test React Native 

## Review and Testing Steps

1. Pull the branch 
2. Go to "app/client/mindjogg"
3. Run ``` npm test ``` to run a test.

## Additional Informations (If aplicable)
yarn.lock is included to download RNTL because npm showing some unexpected errors. 
### Notes
It can be used for both unit testing regression testing 

### Resources 
Overview: https://reactnative.dev/docs/testing-overview
Jest: https://jestjs.io/docs/tutorial-react-native
RNTL: https://callstack.github.io/react-native-testing-library/

Learning Resource: https://www.reactnativeschool.com/test-react-native-apps-with-react-native-testing-library

### CODE REVIEW

**Review by DemiAdisa — APPROVED** [review]
Set Up looks solid

**Comment by sontushkpaul** [comment]
> Set Up looks solid

@DemiAdisa Did you check the code locally in your machine?

**Comment by DemiAdisa** [comment]
> > Set Up looks solid
> 
> @DemiAdisa Did you check the code locally in your machine?

Not yet, I did not because it was just a set up but if you would like me to, let me know.

**Review by jyaneshseeam — APPROVED** [review]
I ran the code, the test works!

**Pull request merged**
