### PR TITLE
Dev form research

### LINKED ISSUE #44: Decide on implementing or creating a component for web forms
## Context
The application will feature a number of input forms, particularly around account management

## Problem
Forms are unyieldy and hard to maintain by default. We should use a component to make managing them easier and make updating them simple

## Solution
- [x] Research [Formly](http://formly-js.github.io/react-formly/)
- [x] Research any other form libraries
- [x] Decide if we should import a library or make our own component
- [x] Create a new issue either for creating a component or for installing a library

### PR DESCRIPTION
**Pull request by DemiAdisa**
# Form Research

## Source 
Closes #44
Opens up #83 

## Description 
Research needed to be done about how we would manage our forms in the app. After doing some research, I have come across an npm package called Formik which seems extremely promising.

## Summary of PR 
In this PR, I renamed the "research" folder to "documentation" and included a new document called formik.
Contains information about the formik package, please view it when ready.

## Purpose 
To attend to the form component issue we were deliberating.

## Review and Testing Steps
- [ ] Pull dev_form_research branch
- [ ] Ensure you can open and read the formik.md file in the dir: app/documentation/formik.md
- [ ] What do you think? Let us know

## Additional Information (If applicable)
Nil

### Notes
Nil

### Resources 
You can see more about it on [here](https://formik.org/docs/overview)

### CODE REVIEW

**Comment by ja-chisholm** [comment]
Do you know if Formik let us custom components as form fields?

**Comment by DemiAdisa** [comment]
> Do you know if Formik let us custom components as form fields?

Yes it is pretty flexible, it has a component you can include (<Field/> tag) in a component you wish to edit

**Comment by DemiAdisa** [comment]
> > Do you know if Formik let us custom components as form fields?
> 
> Yes it is pretty flexible, it has a component you can include (<Field/> tag) in a component you wish to edit

It didn't come up but there is a Field component included in the formik package you can include in other components

**Review by ja-chisholm — APPROVED** [review]

**Review by jyaneshseeam — APPROVED** [review]
Formik is good

**Pull request merged**
