### PR TITLE
Dev eslint setup

### LINKED ISSUE #15: Set up ESLint
Context: There is currently no linting in the project or as part of CI/CD

Problem: There should be linting

Solution:
- [x] Install ESLint in the client and server
- [x] Define linting and code standards for ESLint
- [x] Update package.json in the client and server
- [x] Update main.yml to add linting to the pipeline

### PR DESCRIPTION
**Pull request by ja-chisholm**
# Pull Request Name
ESLint setup

## Source 
Closes #15 

## Description 
Adds linting to the client and server

### Summary of PR  
Updates package.json and adds ESLint config files to the client and the server 

### Purpose 
Allow code linting to be run from the command line and as part of CI/CD

## Review and Testing Steps
- Pull the latest version of this branch
- Run `npm run lint` and ESLint should run on all files

## Additional Information (If applicable)
N/A

### Notes
ESLint can be reconfigured at any time via `npm init @eslint/config`

### Resources 
ESlint documentation https://eslint.org/

### CODE REVIEW

**Review by jyaneshseeam — APPROVED** [review]
Looks good, works!

**Comment by sontushkpaul** [comment]
@ja-chisholm Found the error 
image

**Comment by sontushkpaul** [comment]
@ja-chisholm do not include the Pull Request in the project as professor asked to avoid.

**Comment by ja-chisholm** [comment]
> @ja-chisholm Found the error image

Fixed in the latest push

**Review by sontushkp — APPROVED** [review]
Tested and it ran perfectly.

**Review by sontushkpaul — APPROVED** [review]
Tested and worked fine

**Pull request merged**
