### PR TITLE
Bug reports, Feature Requests, Pull Requests Templates

### PR DESCRIPTION
**Pull request by sontushkpaul**
## Purpose 

To make the process of the bug reports, feature requests, and pull requests we need a standard template that will be followed by everyone on the team.

## Review and Testing Steps

1.  Go to the files
2.  Check if there are any spelling mistakes or anything that is missing

### Notes
The templates will not work until it is in the master branch. But for safety, we do not merge any PR to master and stage branches for now. 

### Resources 
For further information about GitHub templates checkout the [GitHub Template docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

### CODE REVIEW

**Review by ja-chisholm — APPROVED** [review]
All looks good

**Review by jyaneshseeam — APPROVED** [review]
Looks good!

**Review by DemiAdisa — APPROVED** [review]
All good.

**Comment by sontushkpaul** [comment]
@jyaneshseeam Can you review the Pull-Request and if everything is looks okay merge the pull request?

**Comment by jyaneshseeam** [comment]
All looks good, just merged!

**Comment by sontushkpaul** [comment]
@jyaneshseeam Please make sure if the branch is abundant (if you are not sure ask the person who is responsible for the branch) then delete the branch but remember the "master", "stage","dev" branch are not meant be deleted in any case.

**Pull request merged**
