### PR TITLE
Emergency Call Feature Documentation

### LINKED ISSUE #152: Research on Call Feature
# Context
Our app has a feature that allows users to make emergency calls to the authorities (911). We need a package to be able to implement that feature.

# Problem
Find out what package can implement a call feature in our app

# Solution
- [ ] Research online for packages that can be used to implement this feature
- [ ] Document your findings in a markdown file and include them in the codebase

### PR DESCRIPTION
**Pull request by DemiAdisa**
## Source 

Closes #152 

### Summary of PR 

This PR includes a markdown file in the documentation folder and also includes a new dependency for our emergency call feature.

### Purpose 

To include research findings to the codebase

### Review and Testing Steps

- [ ] Pull this branch
- [ ] Navigate to app\documentation\phonecall_package.md and take a read at it and visit the links
- [ ] Check the client package.json file has the dependency mentioned in the documentation
- [ ] Leave a review/comment

### Additional Information (If applicable)
Nil

### Notes
Nil

### Resources 
Details are in the markdown file

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@DemiAdisa phonecall_package.md file is not in the PR.

**Comment by DemiAdisa** [comment]
> @DemiAdisa phonecall_package.md file is not in the PR.

Really?? Ok gimme one sec

**Comment by DemiAdisa** [comment]
> @DemiAdisa phonecall_package.md file is not in the PR.

It should be in there now 👌

**Review by ja-chisholm — APPROVED** [review]
The package looks like a good choice

**Review by jyaneshseeam — APPROVED** [review]
seems good

**Pull request merged**
