### PR TITLE
Creation of journal entry backend API + Front end screens basic set up+ Personalized user info 

### LINKED ISSUE #188: Store user info in async storage, front end
# Context
Once user logs in, user info has to be stored in the storage so that it can be accessed by all other screens

# Problem
no persistence of data yet in front end

# Solution
Create a solution using async storage to store user info

### LINKED ISSUE #224: Personal Journal Backend
# Context
we cannot store journal details yet in the backend nor retrieve them

# Problem
Cannot store journal details yet

# Solution
Create an API to store and retrieve journal detail

### LINKED ISSUE #225: Journal entry Front end basic set up
# Context
We cannot view journal entries yet, as there is no implemented code

# Problem

We cannot view journal entries yet in app, as there is no implemented code

# Solution
- [ ] Create basic screens that displays journal entries
- [ ] Connect backend with frond end

### LINKED ISSUE #227: Write test for Journal entry backend
## Context 

An API is needed to populate and fetch data from the database and send it to the front-end app and we have to test the API to make sure it's working correctly.

## Problem 

There are no tests written yet

## Solution 

- [x] Write unit tests for populating the database
- [x] Write unit tests for fetching data from the database

### PR DESCRIPTION
**Pull request by jyaneshseeam**
# Pull Request name

Dev Journal entry (Backend + some front end) and get user info 

## Source 
Closes #188
Closes #225
Closes #224
Closes #227

## Description 
If you log in now you should have your name personalized greetings  up, journal backend fully functional + front end screens set up to add new entry + fetch and display existing entries + detailed screen for journal entry

### Summary of PR  

Emergency support API that returns a list of emergency supports + populating database functionality

### Purpose 
Creation of journal entry backend API + Front end screens basic set up+ Personalized user info 

## Review and Testing Steps
- [ ] you can just check if all tests pass, if you want to play around with the API follow the steps below
- [ ] Pull this branch
- [ ] Run  ``` cd app\server ```
- [ ] create a .env file and get the values from the shared doc from https://docs.google.com/document/d/1sprMBncWt9RDJSFmwBZRFc_Gg_Zg0lG9kvmOKvTmca8/edit
- [ ]  run ``` npm install```
- [ ] run ``` docker build -t server . ```
- [ ] run ``` docker run -dp 8080:8080 server ```
- [ ] Then go to client folder cd app\client\mindjogg
- [ ] run ``` npm install```
- [ ] Please update your ip address in the following files below:
        - App.js line 74
        - EmergencySupportMainScreen.js line 14
        - PositiveJournalMainScreen.js line 10
        - PositiveJournalEditScreen.js line 9
- [ ] run  ``` npm start```
- [ ] Create a new account by registering, this step is very important as user schema has been modified it won't work with credentials created before that
- [ ] Once registered , login with the newly created credentials
- [ ] Check Home screen should have your first name displayed
- [ ] Check personal journal screen
- [ ] Add new entry
- [ ] Check on cards to view entry details

### CODE REVIEW

**Comment by DemiAdisa** [comment]
image

I get this error when I try it out, tests run fine though

**Comment by jyaneshseeam** [comment]
> image
> 
> I get this error when I try it out, tests run fine though

Did you change the URL to your IP address everywhere?

**Comment by DemiAdisa** [comment]
I still get the error even after the recent bug fix push

**Comment by DemiAdisa** [comment]
> > image
> > I get this error when I try it out, tests run fine though
> 
> Did you change the URL to your IP address everywhere?

Yes, for reference, this is what I got on all the specified pages 
const backend = "http://192.168.2.35:8080";

**Comment by jyaneshseeam** [comment]
> I still get the error even after the recent bug fix push

Is the docker running ?

**Comment by DemiAdisa** [comment]
> > I still get the error even after the recent bug fix push
> 
> Please update your IP address every where mentioned in the pr

Yeah I have already given that a go👌

**Comment by DemiAdisa** [comment]
> > I still get the error even after the recent bug fix push
> 
> Is the docker running ?

Yes

**Comment by jyaneshseeam** [comment]
> > > I still get the error even after the recent bug fix push
> > 
> > 
> > Please update your IP address every where mentioned in the pr
> 
> Yeah I have already given that a go👌
make sure to register as a new user, old user schema has been modified now
Try double checking if docker is running or not + sign out sign back in to check that

**Comment by jyaneshseeam** [comment]
> > > I still get the error even after the recent bug fix push
> > 
> > 
> > Is the docker running ?
> 
> Yes

make sure to register as a new user, old user schema has been modified now
Try double checking if docker is running or not + sign out sign back in to check that

**Comment by DemiAdisa** [comment]
> > > > I still get the error even after the recent bug fix push
> > > 
> > > 
> > > Please update your IP address every where mentioned in the pr
> > 
> > 
> > Yeah I have already given that a go👌
> > make sure to register as a new user, old user schema has been modified now
> > Try double checking if docker is running or not + sign out sign back in to check that

ok one sec

**Comment by DemiAdisa** [comment]
> > > > I still get the error even after the recent bug fix push
> > > 
> > > 
> > > Is the docker running ?
> > 
> > 
> > Yes
> 
> make sure to register as a new user, old user schema has been modified now Try double checking if docker is running or not + sign out sign back in to check that

What login credentials do you use?

**Comment by jyaneshseeam** [comment]
> > > > > I still get the error even after the recent bug fix push
> > > > 
> > > > 
> > > > Is the docker running ?
> > > 
> > > 
> > > Yes
> > 
> > 
> > make sure to register as a new user, old user schema has been modified now Try double checking if docker is running or not + sign out sign back in to check that
> 
> What login credentials do you use?

you have to register as new user with new password + new username

**Comment by DemiAdisa** [comment]
> > > > > > I still get the error even after the recent bug fix push
> > > > > 
> > > > > 
> > > > > Is the docker running ?
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > make sure to register as a new user, old user schema has been modified now Try double checking if docker is running or not + sign out sign back in to check that
> > 
> > 
> > What login credentials do you use?
> 
> you have to register as new user with new password + new username

Sure thing

**Comment by DemiAdisa** [comment]
image

Entry didn't show up

**Comment by jyaneshseeam** [comment]
> 

I think what i did to fix the undefined thing broke the code, I reversed it , it should work now

**Comment by DemiAdisa** [comment]
> > 
> 
> I think what i did to fix the undefined thing broke the code, I reversed it , it should work now

will give that a go in a bit

**Comment by DemiAdisa** [comment]
Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it

**Comment by DemiAdisa** [comment]
> Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it

image

I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen

**Comment by jyaneshseeam** [comment]
> > Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it
> 
> image
> 
> I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen

Im not sure why its not showing up, try doing npm install and try again?

**Comment by DemiAdisa** [comment]
> > > Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it
> > 
> > 
> > image
> > I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen
> 
> Im not sure why its not showing up, try doing npm install and try again?

No luck, if it doesn't work for others, we can just merge it and I could try fixing it when I am redesigning the screens.

**Comment by DemiAdisa** [comment]
> > > > Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it
> > > 
> > > 
> > > image
> > > I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen
> > 
> > 
> > Im not sure why its not showing up, try doing npm install and try again?
> 
> No luck, if it doesn't work for others, we can just merge it and I could try fixing it when I am redesigning the screens.

I have made an issue for the bug 👌

**Review by DemiAdisa — APPROVED** [review]
Everything is good except the bug, I have made an issue for it so will attend to once it is merged

**Comment by jyaneshseeam** [comment]
> > > > > Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it
> > > > 
> > > > 
> > > > image
> > > > I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen
> > > 
> > > 
> > > Im not sure why its not showing up, try doing npm install and try again?
> > 
> > 
> > No luck, if it doesn't work for others, we can just merge it and I could try fixing it when I am redesigning the screens.
> 
> I have made an issue for the bug 👌

yeah you can try to do it in an issue, 
try doing this and let me know ifit works
npm install @react-native-picker/picker --save

**Comment by DemiAdisa** [comment]
> > > > > > Works great, I just have a question, How exactly is the type attribute of a journal decided? I did not get any chance to choose one or set it
> > > > > 
> > > > > 
> > > > > image
> > > > > I checked the code and it doesn't seem to have the Picker component you implemented in the edit screen
> > > > 
> > > > 
> > > > Im not sure why its not showing up, try doing npm install and try again?
> > > 
> > > 
> > > No luck, if it doesn't work for others, we can just merge it and I could try fixing it when I am redesigning the screens.
> > 
> > 
> > I have made an issue for the bug 👌
> 
> yeah you can try to do it in an issue, try doing this and let me know ifit works npm install @react-native-picker/picker --save

Will give that a go after work today 👍

**Review by ja-chisholm — APPROVED** [review]
Works alright for me and all looks good. Why is the backend set to a local IP instead of the heroku URL though?

**Comment by DemiAdisa** [comment]
> Works alright for me and all looks good. Why is the backend set to a local IP instead of the heroku URL though?

The code on the server has changed so you gotta re run a new server image, can you see the picker component on the positive journal edit page?

**Comment by jyaneshseeam** [comment]
> Works alright for me and all looks good. Why is the backend set to a local IP instead of the heroku URL though?

Yeah once sontush pushes the new code for backend  then we can change it back to the heroku URL.

**Pull request merged**
