### PR TITLE
Dev to  stage

### PR DESCRIPTION
**Pull request by sontushkpaul**
## Purpose 
To merge Pull request #1 "dev" to "stage". 

## Review and Testing Steps

1.  Go to the files
2.  Check if there are any spelling mistakes or anything that is missing

**Note** : It is already tested and reviewed

### Notes
The templates will not work until it is in the master branch. But for safety, we do not merge any PR to master and stage branches for now. 

### Resources 
For further information about GitHub templates checkout the [GitHub Template docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

### CODE REVIEW

**Comment by jyaneshseeam** [comment]
Looks good!

**Comment by sontushkpaul** [comment]
@DemiAdisa @ja-chisholm  @sontushkpaul Please review and approve it. @jyaneshseeam please merge it once everyone has approved it.

**Comment by sontushkpaul** [comment]
I could not find approve option in the PR. I am good with the PR, You can merge it.

**Review by ja-chisholm — APPROVED** [review]
Looks good

**Review by jyaneshseeam — APPROVED** [review]
Looks good

**Pull request merged**
