### PR TITLE
Email automation added 

### LINKED ISSUE #39: Add email automation tool
## Context
we will use [Nodemailer](https://nodemailer.com/about/) library for automated emails 

## Problem
We need a tool for email automation for features like account verification or forget password, reset password

## Solution

- [x] 1. Install nodemailer through npm
- [x] 2. Define transporter(credentials for sender)

Resource: [How to send emails with Node.js with Nodemailer]
(https://www.youtube.com/watch?v=CrdMFZIYoEY)

### LINKED ISSUE #63: Decouple database connection
## Context
We want our app decoupled and module-based so that it is easy to maintain. 

## Problem

The database connection is currently coded inside of the account management app

## Solution 

- [x] Create different file for microservice "database_Connection"
- [x] Implement existing connection to fit microservice
- [x] Add microservice to account management app

### PR DESCRIPTION
**Pull request by jyaneshseeam**
# Pull Request name

Add email automation tool, nodemailer  + sends dummy email to a new user upon registration

## Source 
Closes #39 and #63

## Description 
When new users register, they will get an automated email to verify their profile, this email does not have any active links yet but you can test it would.

### Summary of PR  

Nodemailer added, account creation email added

### Purpose 
Email automation tool

## Review and Testing Steps
[ ] Go to app\server
[ ] Run npm install
Update your .env file with variables found at https://docs.google.com/document/d/1sprMBncWt9RDJSFmwBZRFc_Gg_Zg0lG9kvmOKvTmca8/edit
[ ] Run npm run devStart
[ ] open request.rest file
[ ] register a new user with a real email at localhost:3000/users/register 
I used https://temp-mail.org/en/ this tool for a temporary email to use to test it out, you can too
You should get a welcome email

## Additional Information (If applicable)
Register a new user 

### Notes
you can use a tool like POSTMAN or a tool like Rest client

Copy and paste the request from request.rest for Postman , or perform send request directly from that file for RestClient
Routes are 
localhost:3000/users/register (to register new user)

### CODE REVIEW

**Review by sontushkpaul — APPROVED** [review]
Tested and worked in my end

**Comment by DemiAdisa** [comment]
I got an error unfortunately

**Comment by DemiAdisa** [comment]
> I got an error unfortunately

image

**Review by DemiAdisa — APPROVED** [review]
Sorted out the error, all is good, everything works as expected now

**Pull request merged**
