### PR TITLE
Dev global stylesheet

### LINKED ISSUE #135: Front end global style sheet
## Context

In order to have the same feel throughout the whole app a global style sheet is needed

## Problem 
We don't have style sheet yet and inline style are being used ineach component
## Solution 

- [x] Create stylesheet
- [x] convert figma CSS to code inside of stylesheet

### PR DESCRIPTION
**Pull request by jyaneshseeam**
## Source 

Closes #135

### Summary of PR 

Front end developers need a global style sheet to have all colors in one place

### Purpose 

To centralize all colors in one place for easier access.

### Review and Testing Steps

- [ ] Pull this branch
- [ ] Run "npm install" in the client folder to install dependencies
- [ ] Run "npm start" 
- [ ] Navigate through screens, original design's Figma colors have been added
- [ ] Leave your review, do you think anything else needs to be added to the global stylesheet?

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@jyaneshseeam I do no think we need white background png file we can easily implement that using flexbox

**Comment by DemiAdisa** [comment]
> @jyaneshseeam I do no think we need white background png file we can easily implement that using flexbox

True that

**Review by DemiAdisa — APPROVED** [review]
The stylesheet is a good idea, and if we need to update our style, we can always update the file

**Comment by jyaneshseeam** [comment]
> @jyaneshseeam I do no think we need white background png file we can easily implement that using flexbox

@sontushkpaul  yeah i was wondering the same as it's just a box

**Review by ja-chisholm — APPROVED** [review]
Looks good

**Pull request merged**
