### PR TITLE
Dev hide server errors

### LINKED ISSUE #198: Account Management - Do not show error on 401 or 500 response
## Context
@ja-chisholm Everything looks perfect except the error. It is not super important to fix it right now. If it is a easy fix then please do it if it will take time then leave it for now.
image

Environment:
OS: Android 8
Android emulator

_Originally posted by @sontushkpaul in https://github.com/UPEI-Android/group-project-mindjogg/issues/191#issuecomment-1065988119_

## Problem
Even though all responses from the server are handled, the console still logs errors associated with 401 and 500 response codes.

## Solution
We should somehow suppress these errors so that they aren't shown to the user

### PR DESCRIPTION
**Pull request by ja-chisholm**
# Pull Request name
Hide server errors

## Source 
Closes #198 

### Summary of PR  
Prevents the 400 and 500 server response errors from being logged in the console

### Purpose 
Security obfuscation and ease of use

## Review and Testing Steps
- [ ] Pull this branch
- [ ] Attempt to log in with a non existent account
- [ ] Attempt to log in with an incorrect password but existing username

## Additional Information (If applicable)
N/A

### Notes
N/A

### CODE REVIEW

**Review by jyaneshseeam — APPROVED** [review]

**Comment by jyaneshseeam** [comment]
Once there is one more approval, I'm going to resolve the conflicts to merge it

**Comment by sontushkpaul** [comment]
image
Did not work

**Comment by jyaneshseeam** [comment]
> image Did not work

From what I understand and found out when I researched, the expo just displays this error when its in development, Try to login with wrong credentials in the Published version of the old release in the link you sent to the professor, you will see there is not error displayed. Once front-end is published in expo automatically these errors wont show.

**Comment by sontushkpaul** [comment]
> > image Did not work
> 
> From what I understand and found out when I researched, the expo just displays this error when its in development, Try to login with wrong credentials in the Published version of the old release in the link you sent to the professor, you will see there is not error displayed. Once front-end is published in expo automatically these errors wont show.

Got it

**Review by sontushkpaul — APPROVED** [review]

**Pull request merged**
