### PR TITLE
Dev password box

### LINKED ISSUE #81: Create password box component
## Context
We will need a password component. It should extend textbox, and add hiding/showing the input and make sure whatever input it passes on is encrypted

## Problem
We must make this password component.

## Solution
- [ ] Determine how to implement this component
- [ ] Implement it, making sure that it can be used anywhere a textbox can be used
- [ ] Complete issue #82 for testing

### PR DESCRIPTION
**Pull request by ja-chisholm**
## Source 
Closes #81 

## Description 
A configurable Password box to be used in the login and account creation menus

### Summary of PR 
Adds the Password Box and its documentation. Testing will be added in a separate PR

### Purpose 
The password box will hide input and toggle showing it

### Review and Testing Steps

- [ ] Pull this branch
- [ ] Follow the PasswordBox documentation (in the same folder as the component) to replicate it

### Additional Information (If applicable)
A markdown file can be found in the same folder as the component and its tests

### Notes
Tests are to be added soon: I am having some issue with "react-test-renderer" that I need to resolve first.

### CODE REVIEW

**Comment by jyaneshseeam** [comment]
@ja-chisholm lint is failing

**Comment by sontushkpaul** [comment]
@ja-chisholm Your test is failed. It failed because you have install jest 27. Downgrade to ```"jest": "^26.6.3"``` using following command in terminal ```npm install --save-dev-g jest@26.6.3```

**Comment by sontushkpaul** [comment]
@ja-chisholm I faced same problem like text box
image

**Comment by sontushkpaul** [comment]
@ja-chisholm I faced following error in Android 
image

And Following warning in IOS

image

**Comment by sontushkpaul** [comment]
@ja-chisholm why there is no CI/CD pipeline ?

**Comment by sontushkpaul** [comment]
@ja-chisholm Please make the password box resizable as well

**Comment by ja-chisholm** [comment]
> @ja-chisholm why there is no CI/CD pipeline ?

No idea why the checks weren't showing up, but a pipeline ran for my latest commit so it must be working now

**Comment by sontushkpaul** [comment]
@ja-chisholm The eye button does not working in IOS.

**Comment by ja-chisholm** [comment]
@sontushkpaul the eye-outline icon I was using was apparently made by a third party, but it's now updated to one from Google's icon library

**Comment by DemiAdisa** [comment]
Whats the current status on the Password Box

**Comment by ja-chisholm** [comment]
> Whats the current status on the Password Box

It should be good, unless there are any more changes you guys want made

**Review by jyaneshseeam — APPROVED** [review]
Password box appears and looks good but when I click on the eye button  normal text does not appear, it's just blank is it normal?

**Comment by ja-chisholm** [comment]
> Password box appears and looks good but when I click on the eye button normal text does not appear, it's just blank is it normal?

It's supposed to work like this:
image
then click the eye
image
do you mind sharing your implementation?

**Comment by jyaneshseeam** [comment]
eff
e9fhf
iheifhf

This was the implementation, copied from the documentation, and this is what is happening, the text does not appear, I tested on android phone

**Comment by jyaneshseeam** [comment]
> eff e9fhf iheifhf
> 
> This was the implementation, copied from the documentation, and this is what is happening, the text does not appear, I tested on android phone

It works for me now

**Review by DemiAdisa — APPROVED** [review]
Password Box works, just need to fix the merging conflicts and PR is good to go👍

**Pull request merged**
