### PR TITLE
Dev edit profile screen

### LINKED ISSUE #55: Create edit profile screen
## Context
Please review the issue #53 

## Problem
We do not have the interface (UI in React Native) to edit the user's profile information 

## Solution 

- [ ] add editable test boxes 
- [ ] add submit button

### PR DESCRIPTION
**Pull request by ja-chisholm**
### Summary of PR 
Adds a screen and some functionality for the "edit profile" screen

### Purpose 
To add an "edit profile" screen

Closes #55 and #228

### Review and Testing Steps

- [ ] Pull this branch
- [ ] Login and navigate to "edit profile"
- [ ] Make sure it looks good, buttons are in the right place, and the "logout" button works

### Additional Information (If applicable)
The buttons other than logout don't currently have any functionality

### Resources

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@ja-chisholm is it ready?

**Comment by ja-chisholm** [comment]
> @ja-chisholm is it ready?

Yes, it just needs review. Two of the buttons don't have functionality, because that functionality (show emergency contacts and users' contact information) doesn't exist in the backend yet

**Review by jyaneshseeam — APPROVED** [review]
Works

**Review by DemiAdisa — APPROVED** [review]
All good

**Pull request merged**
