### PR TITLE
Dev moodpicker

### LINKED ISSUE #238: Mood tracker backend Frequency functionality
# Context
We cannot retrieve the frequency of moods yet

# Problem
 cannot retrieve the frequency of moods yet

# Solution
Create a function in the backend to process the frequency of moods past 7 days
Create an API to retrieve the frequency of moods

### PR DESCRIPTION
**Pull request by sontushkpaul**
### Summary of PR 
Adds Mood trackers full feature

### Source
Closes 
#238 
#217 
#216
#182
#181 

### Review and Testing Steps

1.  Pull this branch
2. Start server and app (change IP)
3. Login and navigate to Mood Tracker screen
4. Pick a mood write a note 
5. Save the mood
6.  Go to history screen 
7.  You will see the graph and history of your picked mood

### Additional Information (If applicable)
Check if animation is working properly for graph

### Note 
For now you can delete mood once it is save (Future feature)

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@jyaneshseeam I am not sure what happening with sever tests.  can you check?

**Review by jyaneshseeam — APPROVED** [review]

**Comment by DemiAdisa** [comment]
image

Got this bug, ran NPM install already

**Comment by sontushkpaul** [comment]
> image
> 
> Got this bug, ran NPM install already

Option 1: Delete node_modules from mindjogg then run npm install 
Option 2: Make sure you have "react-native-reanimated"  in your package-lock.json file 
 
image

if not download the package by following the steps https://docs.expo.dev/versions/latest/sdk/reanimated/

Option 3: Clone the branch in a brad new folder and try to run from there but remember to run npm install

**Review by ja-chisholm — APPROVED** [review]
Looks good, the graph generates for me

**Pull request merged**
