### PR TITLE
Smart Goals backend + basic frontend done

### LINKED ISSUE #248: Goals setting basic front-end
# Context
We cannot view the goals yet

# Problem

We cannot view goal entries yet in-app, as there is no implemented code

# Solution
- [x] Create basic screens that display goals and to add goals
- [x] Connect backend with front end

### LINKED ISSUE #249: Goal setting backend api
# Context
we cannot store goal entries yet in the backend nor retrieve them

# Problem
Cannot store goal entries  yet

# Solution
Create an API to store and retrieve  goal entries

### PR DESCRIPTION
**Pull request by jyaneshseeam**
# Pull Request name

Smart goals entry (Backend + some front end)  note: only update line 14 in app.js with backend URL now

## Source 

Closes #249
Closes #248

## Description 
If you log in now you can set goals and view them

### Summary of PR  

Calendar API that updates backend with new date entries for smart goal

### Purpose 
Smart goal API that sets goals

## Review and Testing Steps
- [ ] Pull this branch
- [ ] Run  ``` cd app\server ```
- [ ] create a .env file and get the values from the shared doc from https://docs.google.com/document/d/1sprMBncWt9RDJSFmwBZRFc_Gg_Zg0lG9kvmOKvTmca8/edit
- [ ]  run ``` npm install```
- [ ] run ``` docker build -t server . ```
- [ ] run ``` docker run -dp 8080:8080 server ```
- [ ] Then go to client folder cd app\client\mindjogg
- [ ] run ``` npm install```
- [ ] Please update your IP address in the following files below:
        - App.js line 14
- [ ] run  ``` npm start```
- [ ] Create a new account by registering, if you created a new one after the journal entry pr then don't create a new one use the same credentials
- [ ] Once registered, log in with the newly created credentials
- [ ] Check Smart goals screen
- [ ] Add new goal
- [ ] View goal details

### CODE REVIEW

**Comment by DemiAdisa** [comment]
image

I get this error unfortunately

**Comment by jyaneshseeam** [comment]
> image
> 
> I get this error unfortunately

Make sure you have a backend running, + line 14 in app js changed to your IP + should be  http and not https

**Comment by DemiAdisa** [comment]
> 

Yes I made all those changes specified, still didn't work

**Comment by ja-chisholm** [comment]
When trying to run, I get the message "App not opened from Deep Link" and infinite loading

**Comment by DemiAdisa** [comment]
After the bug fix, Do I need to re-build the server docker image to test it out?

**Comment by jyaneshseeam** [comment]
> After the bug fix, Do I need to re-build the server docker image to test it out?

Yes

**Comment by jyaneshseeam** [comment]
> When trying to run, I get the message "App not opened from Deep Link" and infinite loading

Its fixed try restarting expo on your phone and fetch latest code (app not opened from deep link phrase has been deleted)

**Comment by jyaneshseeam** [comment]
> > After the bug fix, Do I need to re-build the server docker image to test it out?
> 
> Yes

If you want you can just run server using npm start in separate terminal , instead of dockerizing it

**Comment by DemiAdisa** [comment]
Yeah that's what I was gonna do, thanks, will get back to you in a few

**Review by sontushkpaul — APPROVED** [review]

**Comment by DemiAdisa** [comment]
SO it works, I can see the smart goals, but when I add a goal, it doesn't show up on the screen but the server responds by saying "user goal updated". Might just be my computer, it has been giving me issues😂

**Review by ja-chisholm — APPROVED** [review]

**Pull request merged**
