### PR TITLE
Implemented Drawer navigation 

### LINKED ISSUE #115: Add Drawer navigation
## Context
The drawer nav will be another navigation option

## Problem 
The drawer nav has to be implemented in modular way and customized way

## Solution 

- [ ] Create drawer nav
- [ ] Customize drawer nav

### PR DESCRIPTION
**Pull request by sontushkpaul**
## Source 
Closes #115 

### Summary of PR 

The PR introduce drawer navigation for the MindJoGG 
 
### Review and Testing Steps

1.Pull this branch
2. Run  ``` cd app/client/mindjogg ```
3. create a .env file and get the values from the shared doc
4. run ``` npm install```
5. run ```npm start```
6. You will see the drawer nav
7. check if all screens are accessible or not 
  

### Additional Information (If applicable)
only the main screen of each mini app will have hamburger menu

### Notes

The account management main screen will not have hamburger menu

### CODE REVIEW

**Comment by jyaneshseeam** [comment]
@sontushkpaul  linting fails

**Review by ja-chisholm — APPROVED** [review]
Looks good other than linting

**Review by jyaneshseeam — APPROVED** [review]
Looks good too!

**Comment by DemiAdisa** [comment]
Some of the CI checks cleared, also, does this mean issue #85 is no longer needed?

**Pull request merged**
