### PR TITLE
Renamed app/client/mindjogg/app to app_elements

### LINKED ISSUE #61: Research on Ui kits and libraries
## Context

To accompany front end development, UI kits or libraries are often available

## Problem
UI kitten is one of the options, but more research is needed before using it

## Solution
- [ ] Research Ui kits for react native
- [ ] Decide which is more effective for our purposes
- [ ] Describe your choice to the group

### PR DESCRIPTION
**Pull request by DemiAdisa**
# UI Packages Research

## Source 

Closes #61 

### Summary of PR 
Making our own UI might be a little too tasking and time-consuming so we needed to research on which UI package for React Native would be best for us. 
 
### Purpose 
To include the documentation of the research findings

### Review and Testing Steps
- [ ] Pull this branch
- [ ] Navigate to app/documentation/ui_packages.md
- [ ] Read the file and give your review

### Additional Information (If applicable)
Nil

### Notes
Nil

### Resources 
All resources are included in the app/documentation/ui_packages.md file

### CODE REVIEW

**Comment by DemiAdisa** [comment]
Forgot to mention, after we are all in agreeance, I will create an issue to install the UI package dependency and assign it to myself.

**Comment by sontushkpaul** [comment]
@DemiAdisa Please resolve the conflicts

**Comment by DemiAdisa** [comment]
Will do, give me a few minutes

**Comment by DemiAdisa** [comment]
> @DemiAdisa Please resolve the conflicts

Conflicts resolved

**Review by ja-chisholm — APPROVED** [review]
Looks good but why does this PR update a bunch of stuff in the server?

**Review by jyaneshseeam — APPROVED** [review]
@ja-chisholm  I think he is also pushing the old Branch that he tested with his own values for the reset password functionalities from What I see. But I don't see it affect the functionality itself. 
@DammyTheSlayer you can pull the new dev branch merge it to yours so that you have the latest code then commit this branch but all looks good for now. You can do it in the future before doing a pr

**Pull request merged**
