### PR TITLE
Dev Authentication Screen Set up

### PR DESCRIPTION
**Pull request by sontushkpaul**
# Pull Request name

Login API documentation

## Description 

Login API documentation

### Summary of PR  

We need to approve the PR as soon as possible because it contains the basic authentication flow of the app

### Purpose 

Implemented the authentication screens and set up basic authentication flow of the app

## Review and Testing Steps

1. Pull the branch
2. Go to mindjogg folder 
3. run "npm start"
4. Go to sign in screen to authenticate (username: admin, password: password)
5. Exit the app and check if the app needs authentication again (do not sign out now)
6. Sign out and  check if the app allow you to enter the app
7. Go to sign up app and enter the details and submit check the entered data in the console

### Notes
The app does not make any api call yet.

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@ja-chisholm you can clone the dev once the repo is merged

**Comment by ja-chisholm** [comment]
> @ja-chisholm you can clone the dev once the repo is merged

will do

**Comment by ja-chisholm** [comment]
When trying to run on Android I get the uncaught error "global.performance.now is not a function", and if I dismiss the error, the "sign in" button is not visible.

image


image

**Comment by jyaneshseeam** [comment]
@ja-chisholm  for me it's rendering without any errors, try doing npm install again maybe, then run again

**Review by jyaneshseeam — APPROVED** [review]
Looks good, screens works, looks like sign in function and sign up not developed yet, I guess it will be developed by Andrew while it's being connected with the backend

**Comment by sontushkpaul** [comment]
@ja-chisholm Please make sure you have do npm install and you have react native async storage in your package.json file

If it is still not resolve the issue we can have a one to one meet up to resolve the issue

**Comment by sontushkpaul** [comment]
> Looks good, screens works, looks like sign in function and sign up not developed yet, I guess it will be developed by Andrew while it's being connected with the backend

Please Try again it should not give you an error now.

**Review by ja-chisholm — APPROVED** [review]
Everything seems to be working for me!

**Pull request merged**
