### PR TITLE
Add stack Navigator 

### LINKED ISSUE #62: Add stack navigation
## Context

Navigation is a very important aspect of mobile application development.

## Problem

There are some libraries for navigations available already but needs to be implemented

## Solution
- [x] Install React Navigation stack
- [x] Create Necessary Screen for each mini app
- [x] Create Stack Navigator for each mini app

### PR DESCRIPTION
**Pull request by ja-chisholm**
## Source 
Closes #62 

## Description 
Adds only stack navigation

### Summary of PR 
Updates package.json and App.js to easily use navigation

### Purpose 
To allow the creation of a side menu, a bottom tab, and stack navigation

### Review and Testing Steps

- [ ] Pull this branch

- [ ]  Import Different Navigator from navigation folder in App.js one at a time
- [ ] add it in "NavigationContainer" tag

### Additional Information (If applicable)
Check out react navigation's documentation here https://reactnavigation.org/docs/getting-started

### Notes
N/A

### Resources 
https://reactnavigation.org/docs/getting-started

### CODE REVIEW

**Comment by DemiAdisa** [comment]
The CI build failed so you might want to review the PR @ja-chisholm

**Comment by sontushkpaul** [comment]
@ja-chisholm I have encountered the following error while testing the the drawer navigation 
image

**Comment by ja-chisholm** [comment]
> @ja-chisholm I have encountered the following error while testing the the drawer navigation image

What device are you getting this error on? I don't get it on my PC or on my Android phone

**Comment by sontushkpaul** [comment]
> > @ja-chisholm I have encountered the following error while testing the the drawer navigation image
> 
> What device are you getting this error on? I don't get it on my PC or on my Android phone

It is in my physical android phone

**Comment by sontushkpaul** [comment]
@ja-chisholm @jyaneshseeam @DemiAdisa Please review the PR.

**Comment by ja-chisholm** [comment]
There's no option for me to approve but looks good to me

**Comment by sontushkpaul** [comment]
> There's no option for me to approve but looks good to me

It is because you are the author of the PR. You can still test and comment as regular comment

**Review by jyaneshseeam — APPROVED** [review]
Navigator works

**Review by DemiAdisa — APPROVED** [review]
Navigation Works

**Pull request merged**
